# Generated by Django 3.2.15 on 2022-09-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plan_stage_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='day',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual',
            field=models.TimeField(default=None, null=True),
        ),
    ]
