# Generated by Django 3.2.15 on 2022-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual',
            field=models.TimeField(default=None),
        ),
    ]
