# Generated by Django 3.2.15 on 2022-09-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_task_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='actual',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated',
            field=models.DurationField(),
        ),
    ]
