# Generated by Django 3.2.15 on 2022-09-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220908_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='moment',
            field=models.TimeField(),
        ),
    ]
