# Generated by Django 3.2.15 on 2022-09-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_plan_moment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='moment',
            new_name='clock',
        ),
    ]
