# Generated by Django 3.2.15 on 2022-09-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_moment_plan_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='actual',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='estimated',
            field=models.DateTimeField(),
        ),
    ]
