# Generated by Django 3.2.15 on 2022-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220908_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tail',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
